const servicesDataSlug = [
  {
    slug: 'digital',
    titulo: 'Creación de Contenido Digital',
    subtitle: 'Diseñamos contenido multimedia para redes sociales, campañas publicitarias, y más.',
    context: 'La Creación de Contenido Digital es nuestra especialidad: conceptualizamos y producimos material visual estratégico que refuerza tu presencia en redes sociales, websites y campañas. Desde fotografía hasta videos creativos, nuestro enfoque está orientado hacia resultados auténticos y emocionantes.',
    imagen: '/pages/services/digital/digital.jpg',
    images: [
      '/pages/services/digital/digital.jpg',
    ],
  },
  {
    slug: 'quinces',
    titulo: 'Fotografía de 15 Años',
    subtitle: 'Celebra la magia de los 15 años con fotografías que reflejan alegría, belleza y un estilo personalizado.',
    context: 'En un día tan único como tus 15 años, ofrecemos sesiones fotográficas diseñadas para destacar tu esencia y estilo. Nos aseguramos de que cada imagen sea una obra de arte que contarás con orgullo por generaciones. Escenarios creativos, detalles precisos y un toque profesional nos distinguen.',
    imagen: '/pages/services/quinces/quinces.jpg',
    images: [
      '/pages/services/quinces/quinces.jpg',
      '/pages/services/quinces/quinces1.png',
      '/pages/services/quinces/quinces2.png',
      '/pages/services/quinces/quinces3.png',
      '/pages/services/quinces/quinces4.png',
      '/pages/services/quinces/quinces5.png',
    ],
  },
  {
    slug: 'aniversarios',
    titulo: 'Fotografía de Aniversarios',
    subtitle: 'Celebramos tus aniversarios con imágenes que capturan la esencia de tus momentos más especiales.',
    context: 'Los aniversarios merecen ser celebrados con imágenes que cuenten su historia. Ofrecemos sesiones íntimas y artísticas que reflejan la conexión única entre ustedes. Desde locaciones románticas hasta detalles personalizados, cada foto será un testimonio vibrante de su amor.',
    imagen: '/pages/services/aniversarios/aniversarios.jpg',
    images: [
      '/pages/services/aniversarios/aniversarios.jpg',
      '/pages/services/aniversarios/aniversarios1.png',
      '/pages/services/aniversarios/aniversarios2.png',
      '/pages/services/aniversarios/aniversarios3.png',
      '/pages/services/aniversarios/aniversarios4.png',
      '/pages/services/aniversarios/aniversarios5.png',

    ],
  },
  {
    slug: 'babyshowers',
    titulo: 'Fotografía de Baby Showers',
    subtitle: 'Creemos recuerdos inolvidables de la llegada de tu bebé con fotos llenas de ternura y alegría.',
    context: 'La fotografía de Baby Showers es ideal para guardar los recuerdos de un momento tan especial: tu dulce espera. Nuestro equipo captura la alegría y los detalles únicos de este evento familiar, asegurándonos de reflejar la emoción en cada toma.',
    imagen: '/pages/services/babyshowers/babyshowers.jpg',
    images: [
      '/pages/services/babyshowers/babyshowers.jpg',
      '/pages/services/babyshowers/babyshowers1.jpg',
      '/pages/services/babyshowers/babyshowers2.jpg',
    ],
  },
  {
    slug: 'bautizos',
    titulo: 'Fotografía de Bautizos',
    subtitle: 'Inmortalizamos este evento especial con fotos que reflejan la espiritualidad y amor familiar.',
    context: 'El bautizo es una ceremonia cargada de emoción y espiritualidad. Nuestro equipo captura los momentos clave del evento, incluyendo detalles únicos, expresiones de amor y la esencia del día, asegurando que el recuerdo sea tan especial como la ocasión.',
    imagen: '/pages/services/bautizos/bautizos.jpg',
    images: [
      '/pages/services/bautizos/bautizos.jpg',
  
    ],
  },
  {
    slug: 'bodas',
    titulo: 'Fotografía de Bodas',
    subtitle: 'Capturamos los momentos más especiales de tu gran día con un estilo artístico y único, creando recuerdos inolvidables.',
    context: 'En el día más importante de tu vida, nuestras fotografías relatarán la historia completa: los nervios, el amor, la risa y las lágrimas. Ofrecemos un servicio integral que combina talento artístico y técnica, creando imágenes que preservan la magia de tu boda para siempre.',
    imagen: '/pages/services/bodas/boda.jpg',
    images: [
      '/pages/services/bodas/boda.jpg',
      '/pages/services/bodas/bodas.jpg',
      '/pages/services/bodas/bodas1.png',
      '/pages/services/bodas/bodas2.jpg',
      '/pages/services/bodas/bodas3.jpg',
      '/pages/services/bodas/bodas4.jpg',
      '/pages/services/bodas/bodas5.jpg',
      '/pages/services/bodas/bodas6.jpg',
      '/pages/services/bodas/bodas7.jpg',
      '/pages/services/bodas/bodas8.jpg',
      '/pages/services/bodas/bodas9.jpg',
      '/pages/services/bodas/bodas10.jpg',
      '/pages/services/bodas/bodas11.jpg',
      '/pages/services/bodas/bodas12.jpg',
      '/pages/services/bodas/bodas13.jpg',
      '/pages/services/bodas/bodas14.jpg',
      '/pages/services/bodas/bodas15.jpg',
      '/pages/services/bodas/bodas16.jpg',
      '/pages/services/bodas/bodas17.jpg',
      '/pages/services/bodas/bodas18.jpg',
      '/pages/services/bodas/bodas19.jpg',
      '/pages/services/bodas/bodas20.jpg',
      '/pages/services/bodas/bodas21.jpg',
      '/pages/services/bodas/bodas22.jpg',
      '/pages/services/bodas/bodas23.jpg',
      '/pages/services/bodas/bodas24.jpg',
      '/pages/services/bodas/bodas25.jpg',
      '/pages/services/bodas/bodas26.png',
      '/pages/services/bodas/bodas27.jpg',
      '/pages/services/bodas/bodas28.png',
      '/pages/services/bodas/bodas29.jpg',
      '/pages/services/bodas/bodas30.jpg',
      '/pages/services/bodas/bodas31.png',
      '/pages/services/bodas/bodas32.png',
      '/pages/services/bodas/bodas33.jpg',
      '/pages/services/bodas/bodas34.png',
      '/pages/services/bodas/bodas35.jpg',
      '/pages/services/bodas/bodas36.png',
      '/pages/services/bodas/bodas37.jpg',
      '/pages/services/bodas/bodas38.jpg',
      '/pages/services/bodas/bodas39.jpg',
      '/pages/services/bodas/bodas40.jpg',
      '/pages/services/bodas/bodas41.jpg',
      '/pages/services/bodas/bodas42.jpg',
      '/pages/services/bodas/bodas43.jpg',
      '/pages/services/bodas/bodas44.jpg',
      '/pages/services/bodas/bodas45.jpg',
      '/pages/services/bodas/bodas46.jpg',
      '/pages/services/bodas/bodas47.jpg',
      '/pages/services/bodas/bodas48.jpg',
      '/pages/services/bodas/bodas49.jpg',
      '/pages/services/bodas/bodas50.jpg',
      '/pages/services/bodas/bodas51.jpg',
      '/pages/services/bodas/bodas52.png',
    ],
  },
  {
    slug: 'cumples',
    titulo: 'Fotografía de Cumpleaños',
    subtitle: 'Haz que tus celebraciones de cumpleaños sean inolvidables con fotografías llenas de vida y color.',
    context: 'No hay cumpleaños sin recuerdos. Nuestro servicio de fotografía asegura que cada instante, desde los detalles decorativos hasta los momentos espontáneos, quede plasmado en imágenes llenas de vida y color. Creamos retratos y tomas grupales que serán el corazón de tus memorias.',
    imagen: '/pages/services/cumples/cumples.jpg',
    images: [
      '/pages/services/cumples/cumples.jpg',
    ],
  },
  {
    slug: 'eventos',
    titulo: 'Fotografía de Eventos Especiales',
    subtitle: 'Desde aniversarios hasta eventos corporativos, capturamos cada detalle con creatividad y profesionalismo.',
    context: 'Cada evento especial tiene su propio brillo. Nuestro servicio profesional garantiza capturar la esencia de tus reuniones, celebraciones y momentos destacados, con fotografías que van más allá del simple registro, contando una historia visual única.',
    imagen: '/pages/services/eventos/eventos.jpg',
    images: [
      '/pages/services/eventos/eventos.jpg',
      '/pages/services/eventos/eventos1.jpg',
      '/pages/services/eventos/eventos2.png',
      '/pages/services/eventos/eventos3.jpg',
      '/pages/services/eventos/eventos4.png',
      '/pages/services/eventos/eventos5.png',
      '/pages/services/eventos/eventos6.jpg',
      '/pages/services/eventos/eventos7.jpg',
      '/pages/services/eventos/eventos8.jpg',
      '/pages/services/eventos/eventos9.jpg',
      '/pages/services/eventos/eventos10.jpg',
      '/pages/services/eventos/eventos11.jpg',
      '/pages/services/eventos/eventos12.jpg',
    ],
  },
  {
    slug: 'producto',
    titulo: 'Fotografía de Producto',
    subtitle: 'Resalta las características únicas de tus productos con imágenes de alta calidad que captan la atención de tus clientes.',
    context: 'La Fotografía de Producto es esencial para cautivar a tu audiencia. Diseñamos sesiones personalizadas que presentan cada detalle de tu producto con una estética que refuerza la identidad de tu marca. Ideal para catálogos, redes sociales y e-commerce.',
    imagen: '/pages/services/producto/producto.jpg',
    images: [
      '/pages/services/producto/producto.jpg',
    ],
  },
  {
    slug: 'retratos',
    titulo: 'Fotografía de Retratos',
    subtitle: 'Retratos profesionales y artísticos que destacan tu esencia y personalidad en cada imagen.',
    context: 'Los retratos son una forma de arte que reflejan quién eres. Creamos sesiones íntimas y cuidadosamente planificadas, donde cada ángulo, luz y expresión cuentan una historia auténtica. Retratos profesionales ideales para portafolios, recuerdos o regalos.',
    imagen: '/pages/services/retratos/retratos.jpg',
    images: [
      '/pages/services/retratos/retratos.jpg',

    ],
  },
  {
    slug: 'model',
    titulo: 'Fotografía para Modelos',
    subtitle: 'Creamos videos de alta calidad para proyectos personales, comerciales o corporativos con un estilo cinematográfico.',
    context: 'Nuestro servicio especializado para modelos incluye sesiones diseñadas estratégicamente para destacar tus mejores rasgos. Trabajamos en conjunto para lograr imágenes que conquisten agencias y audiencias, abriendo puertas a nuevas oportunidades.',
    imagen: '/pages/services/model/model.jpg',
    images: [
      '/pages/services/model/model.jpg',
      '/pages/services/model/model1.jpg',
      '/pages/services/model/model2.jpg',
      '/pages/services/model/model3.jpg',
      '/pages/services/model/model4.jpg',
      '/pages/services/model/model5.jpg',
      '/pages/services/model/model6.jpg',
      '/pages/services/model/model7.jpg',
      '/pages/services/model/model8.jpg',
    ],
  },
  {
    slug: 'audiovisual',
    titulo: 'Producción Audiovisual',
    subtitle: 'Creamos videos de alta calidad para proyectos personales, comerciales o corporativos con un estilo cinematográfico.',
    context: 'La Producción Audiovisual es el arte de contar historias a través de imágenes en movimiento. Desde videos corporativos hasta documentales y anuncios, nuestro equipo transforma ideas en producciones de alta calidad. Cada proyecto combina creatividad y técnica para alcanzar un impacto memorable.',
    imagen: '/pages/services/audiovisual/audiovisual.jpg',
    images: [
      '/pages/services/audiovisual/audiovisual.jpg',
    ],
  },
];

export default servicesDataSlug;